## PyliPD

This notebook serves as a test for using and evaluating the agent on PyliPD files through either local files or urls.

In [18]:
from pylipd.lipd import LiPD

In [21]:
D_remote = LiPD()
D_remote.set_endpoint("https://linkedearth.graphdb.mint.isi.edu/repositories/LiPDVerse-dynamic")
D_remote.load_remote_datasets(["Ocn-RedSea.Felis.2000"])
print("Loaded:", D_remote.get_all_dataset_names())

type(D_remote)

Caching datasets from remote endpoint..
Making remote query to endpoint: https://linkedearth.graphdb.mint.isi.edu/repositories/LiPDVerse-dynamic
Done..
Loaded: ['Ocn-RedSea.Felis.2000']

pylipd.lipd.LiPD

In [ ]:
D_url = LiPD()
D_url.load(["https://lipdverse.org/data/LCf20b99dfe8d78840ca60dfb1f832b9ec/1_0_1/Nunalleq.Ledger.2018.lpd"])
print("Loaded:", D_url.get_all_dataset_names())
D_url.get_timeseries_essentials()[["dataSetName", "paleoData_variableName", "paleoData_units"]]

In [20]:
data_path = 'Ocn-Palmyra.Nurhati.2011.lpd'
D = LiPD()
D.load(data_path)
type(D)

Loading 1 LiPD files

100%|██████████| 1/1 [00:00<00:00, 27.19it/s]

Loaded..

pylipd.lipd.LiPD

In [7]:
ts_list = D.get_timeseries(D.get_all_dataset_names())

type(ts_list)

Extracting timeseries from dataset: Ocn-Palmyra.Nurhati.2011 ...

dict

In [9]:
ts_list, df = D.get_timeseries(D.get_all_dataset_names(), to_dataframe=True)

df

Extracting timeseries from dataset: Ocn-Palmyra.Nurhati.2011 ...

,mode,time_id,archiveType,hasUrl,dataContributor,originalDataURL,lipdVersion,dataSetName,studyName,pub1_author,...,paleoData_values,paleoData_inferredVariableType,paleoData_dataType,paleoData_description,paleoData_inCompilation,paleoData_ocean2kID,paleoData_qCCertification,paleoData_iso2kUI,paleoData_pages2kID,paleoData_interpretation
0,paleoData,age,Coral,https://data.mint.isi.edu/files/lipd/Ocn-Palmy...,{'name': 'HLF MNE'},http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=...,1.3,Ocn-Palmyra.Nurhati.2011,Nurhati2011_Palmyra,I.S. Nurhati,...,"[0.39, 0.35, 0.35, 0.35, 0.36, 0.22, 0.33, 0.3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,paleoData,age,Coral,https://data.mint.isi.edu/files/lipd/Ocn-Palmy...,{'name': 'HLF MNE'},http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=...,1.3,Ocn-Palmyra.Nurhati.2011,Nurhati2011_Palmyra,I.S. Nurhati,...,"[1998.21, 1998.13, 1998.04, 1997.96, 1997.88, ...",Year,float,Year AD,NaN,NaN,NaN,NaN,NaN,NaN
2,paleoData,age,Coral,https://data.mint.isi.edu/files/lipd/Ocn-Palmy...,{'name': 'HLF MNE'},http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=...,1.3,Ocn-Palmyra.Nurhati.2011,Nurhati2011_Palmyra,I.S. Nurhati,...,"[1998.29, 1998.21, 1998.13, 1998.04, 1997.96, ...",Year,float,Year AD,NaN,NaN,NaN,NaN,NaN,NaN
3,paleoData,age,Coral,https://data.mint.isi.edu/files/lipd/Ocn-Palmy...,{'name': 'HLF MNE'},http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=...,1.3,Ocn-Palmyra.Nurhati.2011,Nurhati2011_Palmyra,I.S. Nurhati,...,"[8.96, 8.9, 8.91, 8.94, 8.92, 8.89, 8.87, 8.81...",NaN,NaN,NaN,Ocean2k_v1.0.0,PacificNurhati2011,"MNE, NJA",CO11NUPM01BT1,Ocn_129,"[{'variableDetail': 'sea@surface', 'scope': 'c..."
4,paleoData,age,Coral,https://data.mint.isi.edu/files/lipd/Ocn-Palmy...,{'name': 'HLF MNE'},http://hurricane.ncdc.noaa.gov/pls/paleox/f?p=...,1.3,Ocn-Palmyra.Nurhati.2011,Nurhati2011_Palmyra,I.S. Nurhati,...,"[-5.41, -5.47, -5.49, -5.43, -5.48, -5.53, -5....",NaN,NaN,NaN,NaN,NaN,"MNE, NJA",CO11NUPM01B,NaN,"[{'variableDetail': 'sea_surface', 'direction'..."

In [10]:
df.columns

Index(['mode', 'time_id', 'archiveType', 'hasUrl', 'dataContributor',
       'originalDataURL', 'lipdVersion', 'dataSetName', 'studyName',
       'pub1_author', 'pub1_citeKey', 'pub1_title', 'pub1_institution',
       'pub1_url', 'pub1_urldate', 'pub2_author', 'pub2_year', 'pub2_citeKey',
       'pub2_volume', 'pub2_DOI', 'pub2_title', 'pub2_pages', 'pub2_journal',
       'pub2_dataUrl', 'pub2_publisher', 'pub3_author', 'pub3_issue',
       'pub3_citeKey', 'pub3_DOI', 'pub3_pages', 'pub3_title', 'pub3_year',
       'pub3_publisher', 'pub3_dataUrl', 'pub3_volume', 'pub3_journal',
       'googleDataURL', 'googleMetadataWorksheet', 'geo_meanLon',
       'geo_meanLat', 'geo_meanElev', 'geo_type', 'geo_ocean', 'geo_siteName',
       'geo_pages2kRegion', 'googleSpreadSheetKey', 'createdBy', 'tableType',
       'paleoData_measurementTableMD5', 'paleoData_measurementTableName',
       'paleoData_paleoDataTableName', 'paleoData_googleWorkSheetKey',
       'paleoData_filename', 'year', 'yearUnits', 'paleoData_variableType',
       'paleoData_TSid', 'paleoData_hasMaxValue', 'paleoData_wDSPaleoUrl',
       'paleoData_resolution_hasMaxValue', 'paleoData_resolution_hasMeanValue',
       'paleoData_resolution_hasMinValue',
       'paleoData_resolution_hasMedianValue', 'paleoData_resolution_units',
       'paleoData_useInGlobalTemperatureAnalysis', 'paleoData_sensorGenus',
       'paleoData_hasMinValue', 'paleoData_variableName',
       'paleoData_hasMeanValue', 'paleoData_missingValue',
       'paleoData_proxyObservationType', 'paleoData_number',
       'paleoData_hasMedianValue', 'paleoData_notes',
       'paleoData_sensorSpecies', 'paleoData_units', 'paleoData_proxy',
       'paleoData_archiveType', 'paleoData_values',
       'paleoData_inferredVariableType', 'paleoData_dataType',
       'paleoData_description', 'paleoData_inCompilation',
       'paleoData_ocean2kID', 'paleoData_qCCertification', 'paleoData_iso2kUI',
       'paleoData_pages2kID', 'paleoData_interpretation'],
      dtype='str')

In [11]:
df['paleoData_variableName']

0     d18O
1     year
2     year
3    Sr/Ca
4     d18O
Name: paleoData_variableName, dtype: str

In [12]:
df[['paleoData_variableName','paleoData_notes']]

  paleoData_variableName                                    paleoData_notes
0                   d18O  d18Osw (residuals calculated from coupled SrCa...
1                   year                                                NaN
2                   year                                                NaN
3                  Sr/Ca  ; paleoData_variableName changed - was origina...
4                   d18O  Duplicate of modern d18O record presented in C...

In [13]:
df_cut = df.iloc[4,:]

df_cut

mode                                                                 paleoData
time_id                                                                    age
archiveType                                                              Coral
hasUrl                       https://data.mint.isi.edu/files/lipd/Ocn-Palmy...
dataContributor                                            {'name': 'HLF MNE'}
                                                   ...
paleoData_ocean2kID                                                        NaN
paleoData_qCCertification                                             MNE, NJA
paleoData_iso2kUI                                                  CO11NUPM01B
paleoData_pages2kID                                                        NaN
paleoData_interpretation     [{'variableDetail': 'sea_surface', 'direction'...
Name: 4, Length: 88, dtype: object

In [14]:
df_cut['paleoData_variableName']

'd18O'

In [15]:
df_essential = D.get_timeseries_essentials()

df_essential

,dataSetName,archiveType,geo_meanLat,geo_meanLon,geo_meanElev,paleoData_variableName,paleoData_values,paleoData_units,paleoData_proxy,paleoData_proxyGeneral,time_variableName,time_values,time_units,depth_variableName,depth_values,depth_units
0,Ocn-Palmyra.Nurhati.2011,Coral,5.87,-162.13,-10.0,d18O,"[-5.41, -5.47, -5.49, -5.43, -5.48, -5.53, -5....",permil,d18O,None,year,"[1998.29, 1998.21, 1998.13, 1998.04, 1997.96, ...",yr AD,None,None,None
1,Ocn-Palmyra.Nurhati.2011,Coral,5.87,-162.13,-10.0,Sr_Ca,"[8.96, 8.9, 8.91, 8.94, 8.92, 8.89, 8.87, 8.81...",mmol/mol,Sr/Ca,None,year,"[1998.29, 1998.21, 1998.13, 1998.04, 1997.96, ...",yr AD,None,None,None
2,Ocn-Palmyra.Nurhati.2011,Coral,5.87,-162.13,-10.0,d18O,"[0.39, 0.35, 0.35, 0.35, 0.36, 0.22, 0.33, 0.3...",permil,d18O,None,year,"[1998.21, 1998.13, 1998.04, 1997.96, 1997.88, ...",yr AD,None,None,None

In [16]:
df_essential.columns

Index(['dataSetName', 'archiveType', 'geo_meanLat', 'geo_meanLon',
       'geo_meanElev', 'paleoData_variableName', 'paleoData_values',
       'paleoData_units', 'paleoData_proxy', 'paleoData_proxyGeneral',
       'time_variableName', 'time_values', 'time_units', 'depth_variableName',
       'depth_values', 'depth_units'],
      dtype='str')

## Second Dataset Import
Can load directories besides invididual files

In [5]:
path = 'Pages2k/'

D_dir = LiPD()
D_dir.load_from_dir(path)

Loading 17 LiPD files

100%|██████████| 17/17 [00:00<00:00, 75.50it/s]

Loaded..

In [6]:
df_dir = D_dir.get_timeseries_essentials()

In [7]:
df_dir.head()

,dataSetName,archiveType,geo_meanLat,geo_meanLon,geo_meanElev,paleoData_variableName,paleoData_values,paleoData_units,paleoData_proxy,paleoData_proxyGeneral,time_variableName,time_values,time_units,depth_variableName,depth_values,depth_units
0,Ocn-RedSea.Felis.2000,Coral,27.8500,34.3200,-6.0,d18O,"[-4.12, -3.82, -3.05, -3.02, -3.62, -3.96, -3....",permil,d18O,None,year,"[1995.583, 1995.417, 1995.25, 1995.083, 1994.9...",yr AD,NaN,None,NaN
1,Ant-WAIS-Divide.Severinghaus.2012,Borehole,-79.4630,-112.1250,1766.0,temperature,"[-29.607, -29.607, -29.606, -29.606, -29.605, ...",degC,borehole,None,year,"[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...",yr AD,NaN,None,NaN
2,Ant-WAIS-Divide.Severinghaus.2012,Borehole,-79.4630,-112.1250,1766.0,uncertainty_temperature,"[1.327, 1.328, 1.328, 1.329, 1.33, 1.33, 1.331...",degC,NaN,None,year,"[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...",yr AD,NaN,None,NaN
3,Asi-SourthAndMiddleUrals.Demezhko.2007,Borehole,55.0000,59.5000,1900.0,temperature,"[0.166, 0.264, 0.354, 0.447, 0.538, 0.62, 0.68...",degC,borehole,None,year,"[800, 850, 900, 950, 1000, 1050, 1100, 1150, 1...",yr AD,NaN,None,NaN
4,Ocn-AlboranSea436B.Nieto-Moreno.2013,Marine sediment,36.2053,-4.3133,-1108.0,temperature,"[18.79, 19.38, 19.61, 18.88, 18.74, 19.25, 18....",degC,alkenone,None,year,"[1999.07, 1993.12, 1987.17, 1975.26, 1963.36, ...",yr AD,NaN,None,NaN

In [8]:
df_dir.shape

(28, 16)

In [9]:
df_dir['paleoData_variableName'].unique()

<StringArray>
[                   'd18O',             'temperature',
 'uncertainty_temperature',                   'notes',
                   'Mg_Ca',                   'Sr_Ca',
                    'Uk37',                   'trsgi',
                     'MXD']
Length: 9, dtype: str

In [10]:
df_temp = df_dir[df_dir['paleoData_variableName']=='temperature']
df_temp.head()

,dataSetName,archiveType,geo_meanLat,geo_meanLon,geo_meanElev,paleoData_variableName,paleoData_values,paleoData_units,paleoData_proxy,paleoData_proxyGeneral,time_variableName,time_values,time_units,depth_variableName,depth_values,depth_units
1,Ant-WAIS-Divide.Severinghaus.2012,Borehole,-79.4630,-112.1250,1766.0,temperature,"[-29.607, -29.607, -29.606, -29.606, -29.605, ...",degC,borehole,None,year,"[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...",yr AD,NaN,None,NaN
3,Asi-SourthAndMiddleUrals.Demezhko.2007,Borehole,55.0000,59.5000,1900.0,temperature,"[0.166, 0.264, 0.354, 0.447, 0.538, 0.62, 0.68...",degC,borehole,None,year,"[800, 850, 900, 950, 1000, 1050, 1100, 1150, 1...",yr AD,NaN,None,NaN
4,Ocn-AlboranSea436B.Nieto-Moreno.2013,Marine sediment,36.2053,-4.3133,-1108.0,temperature,"[18.79, 19.38, 19.61, 18.88, 18.74, 19.25, 18....",degC,alkenone,None,year,"[1999.07, 1993.12, 1987.17, 1975.26, 1963.36, ...",yr AD,NaN,None,NaN
8,Ocn-FeniDrift.Richter.2009,Marine sediment,55.5000,-13.9000,-2543.0,temperature,"[12.94, 10.99, 10.53, 10.44, 11.39, 13.38, 10....",degC,Mg/Ca,None,year,"[1998, 1987, 1975, 1962, 1949, 1936, 1924, 191...",yr AD,NaN,None,NaN
12,Ocn-FeniDrift.Richter.2009,Marine sediment,55.5000,-13.9000,-2543.0,temperature,"[12.94, 10.99, 10.53, 10.44, 11.39, 13.38, 10....",degC,NaN,None,year,"[1998, 1987, 1975, 1962, 1949, 1936, 1924, 191...",yr AD,depth_bottom,"[0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, ...",cm

In [11]:
df_filt = df_dir.query("paleoData_variableName in ('temperature','MXD','Mg_Ca','d18O','trsgi', 'Uk37')")
df_filt.head()

,dataSetName,archiveType,geo_meanLat,geo_meanLon,geo_meanElev,paleoData_variableName,paleoData_values,paleoData_units,paleoData_proxy,paleoData_proxyGeneral,time_variableName,time_values,time_units,depth_variableName,depth_values,depth_units
0,Ocn-RedSea.Felis.2000,Coral,27.8500,34.3200,-6.0,d18O,"[-4.12, -3.82, -3.05, -3.02, -3.62, -3.96, -3....",permil,d18O,None,year,"[1995.583, 1995.417, 1995.25, 1995.083, 1994.9...",yr AD,NaN,None,NaN
1,Ant-WAIS-Divide.Severinghaus.2012,Borehole,-79.4630,-112.1250,1766.0,temperature,"[-29.607, -29.607, -29.606, -29.606, -29.605, ...",degC,borehole,None,year,"[8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,...",yr AD,NaN,None,NaN
3,Asi-SourthAndMiddleUrals.Demezhko.2007,Borehole,55.0000,59.5000,1900.0,temperature,"[0.166, 0.264, 0.354, 0.447, 0.538, 0.62, 0.68...",degC,borehole,None,year,"[800, 850, 900, 950, 1000, 1050, 1100, 1150, 1...",yr AD,NaN,None,NaN
4,Ocn-AlboranSea436B.Nieto-Moreno.2013,Marine sediment,36.2053,-4.3133,-1108.0,temperature,"[18.79, 19.38, 19.61, 18.88, 18.74, 19.25, 18....",degC,alkenone,None,year,"[1999.07, 1993.12, 1987.17, 1975.26, 1963.36, ...",yr AD,NaN,None,NaN
5,Eur-SpannagelCave.Mangini.2005,Speleothem,47.1000,11.6000,2347.0,d18O,"[-7.49, -7.41, -7.36, -7.15, -7.28, -6.99, -6....",permil,d18O,None,year,"[1935.0, 1932.0, 1930.0, 1929.0, 1929.0, 1928....",yr AD,NaN,None,NaN

In [13]:
D_dir.get_all_dataset_names()

['Ocn-RedSea.Felis.2000',
 'Ant-WAIS-Divide.Severinghaus.2012',
 'Asi-SourthAndMiddleUrals.Demezhko.2007',
 'Ocn-AlboranSea436B.Nieto-Moreno.2013',
 'Eur-SpannagelCave.Mangini.2005',
 'Ocn-FeniDrift.Richter.2009',
 'Eur-LakeSilvaplana.Trachsel.2010',
 'Ocn-Palmyra.Nurhati.2011',
 'Ocn-PedradeLume-CapeVerdeIslands.Moses.2006',
 'Ocn-SinaiPeninsula_RedSea.Moustafa.2000',
 'Eur-NorthernSpain.Martin-Chivelet.2011',
 'Arc-Kongressvatnet.D_Andrea.2012',
 'Eur-CoastofPortugal.Abrantes.2011',
 'Eur-SpanishPyrenees.Dorado-Linan.2012',
 'Eur-FinnishLakelands.Helama.2014',
 'Eur-NorthernScandinavia.Esper.2012',
 'Eur-Stockholm.Leijonhufvud.2009']

In [ ]:
D_src = LiPD()
D_src.set_endpoint("https://linkedearth.graphdb.mint.isi.edu/repositories/LiPDVerse-dynamic")
D_src.load_remote_datasets(["MD98_2181.Stott.2007", "Ocn-MadangLagoonPapuaNewGuinea.Kuhnert.2001"])

dses = D_src.get_datasets()
print(f"Got {len(dses)} Dataset objects, type: {type(dses[0])}")

D_reloaded = LiPD()
D_reloaded.load_datasets(dses)
print("Reloaded:", D_reloaded.get_all_dataset_names())

## Deduplication test
Merge the local Nurhati dataset (D) with the Pages2k directory (D_dir), which also contains Nurhati. The agent should only cite Ocn-Palmyra.Nurhati.2011 once.

In [ ]:
import pandas as pd

df_local = D.get_timeseries_essentials()
df_pages2k = D_dir.get_timeseries_essentials()

df_merged = pd.concat([df_local, df_pages2k], ignore_index=True)
print(f"Combined rows: {len(df_merged)}")
print(f"Unique datasets: {df_merged['dataSetName'].nunique()}")
print(df_merged['dataSetName'].unique())

In [14]:
bibs, df = D_dir.get_bibtex(remote = True, save = True, path = 'mybiblio.bib', verbose = True)

Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (http://nbn-resolving.de/urn:nbn:de:gbv:46-ep000102745), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
Cannot find a matching record for the provided DOI (nan), creating the entry manually
['@misc{felis2000httpswwwncdcnoaagovpaleostudy1861DataCitation,\n    author = "T. Felis",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/1861"\n}\n', ' @article{Felis_2000, title={A coral oxygen isotope record from the northern Red Sea documenting NAO, ENSO, and North Pacific teleconnections on Middle East climate variability since the year 1750}, volume={15}, ISSN={1944-9186}, url={http://dx.doi.org/10.1029/1999PA000477}, DOI={10.1029/1999pa000477}, number={6}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Felis, Thomas and Pätzold, Jürgen and Loya, Yossi and Fine, Maoz and Nawar, Ahmed H. and Wefer, Gerold}, year={2000}, month=Dec, pages={679–694} }\n', ' @article{Tierney_2015, title={Tropical sea surface temperatures for the past four centuries reconstructed from coral archives}, volume={30}, ISSN={1944-9186}, url={http://dx.doi.org/10.1002/2014PA002717}, DOI={10.1002/2014pa002717}, number={3}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Tierney, Jessica E. and Abram, Nerilie J. and Anchukaitis, Kevin J. and Evans, Michael N. and Giry, Cyril and Kilbourne, K. Halimeda and Saenger, Casey P. and Wu, Henry C. and Zinke, Jens}, year={2015}, month=Mar, pages={226–252} }\n', '@misc{severinghaus0thisstudyDataCitation,\n    author = "Severinghaus J.",\n    title = "This study",\n    url = "This study"\n}\n', ' @article{Orsi_2012, title={Little Ice Age cold interval in West Antarctica: Evidence from borehole temperature at the West Antarctic Ice Sheet (WAIS) Divide}, volume={39}, ISSN={1944-8007}, url={http://dx.doi.org/10.1029/2012GL051260}, DOI={10.1029/2012gl051260}, number={9}, journal={Geophysical Research Letters}, publisher={American Geophysical Union (AGU)}, author={Orsi, Anais J. and Cornuelle, Bruce D. and Severinghaus, Jeffrey P.}, year={2012}, month=May }\n', ' @article{Demezhko_2007, title={Climatic changes in the Urals over the past millennium – an analysis of geothermal and meteorological data}, volume={3}, ISSN={1814-9332}, url={http://dx.doi.org/10.5194/cp-3-237-2007}, DOI={10.5194/cp-3-237-2007}, number={2}, journal={Climate of the Past}, publisher={Copernicus GmbH}, author={Demezhko, D. Yu. and Golovanova, I. V.}, year={2007}, month=May, pages={237–242} }\n', '@misc{demezhko0thisstudyDataCitation,\n    author = "D Demezhko",\n    title = "This study",\n    url = "this study"\n}\n', ' @article{Nieto_Moreno_2013, title={Climate conditions in the westernmost Mediterranean over the last two millennia: An integrated biomarker approach}, volume={55}, ISSN={0146-6380}, url={http://dx.doi.org/10.1016/j.orggeochem.2012.11.001}, DOI={10.1016/j.orggeochem.2012.11.001}, journal={Organic Geochemistry}, publisher={Elsevier BV}, author={Nieto-Moreno, V. and Martínez-Ruiz, F. and Willmott, V. and García-Orellana, J. and Masqué, P. and Sinninghe Damsté, J.S.}, year={2013}, month=Feb, pages={1–10} }\n', ' @article{McGregor_2015, title={Robust global ocean cooling trend for the pre-industrial Common Era}, volume={8}, ISSN={1752-0908}, url={http://dx.doi.org/10.1038/ngeo2510}, DOI={10.1038/ngeo2510}, number={9}, journal={Nature Geoscience}, publisher={Springer Science and Business Media LLC}, author={McGregor, Helen V. and Evans, Michael N. and Goosse, Hugues and Leduc, Guillaume and Martrat, Belen and Addison, Jason A. and Mortyn, P. Graham and Oppo, Delia W. and Seidenkrantz, Marit-Solveig and Sicre, Marie-Alexandrine and Phipps, Steven J. and Selvaraj, Kandasamy and Thirumalai, Kaustubh and Filipsson, Helena L. and Ersek, Vasile}, year={2015}, month=Aug, pages={671–677} }\n', '@misc{nieto2012httpdoipangaeade101594pangaea802259DataCitation,\n    author = "V. Nieto-Moreno",\n    title = "PANGAEA",\n    institution = "PANGAEA",\n    url = "http://doi.pangaea.de/10.1594/PANGAEA.802259"\n}\n', '@misc{mangini2005httpwwwncdcnoaagovpaleostudy5433DataCitation,\n    author = "A. Mangini",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/5433"\n}\n', ' @article{Mangini_2005, title={Reconstruction of temperature in the Central Alps during the past 2000 yr from a δ18O stalagmite record}, volume={235}, ISSN={0012-821X}, url={http://dx.doi.org/10.1016/j.epsl.2005.05.010}, DOI={10.1016/j.epsl.2005.05.010}, number={3-4}, journal={Earth and Planetary Science Letters}, publisher={Elsevier BV}, author={Mangini, A. and Spötl, C. and Verdes, P.}, year={2005}, month=July, pages={741–751} }\n', ' @article{McGregor_2015, title={Robust global ocean cooling trend for the pre-industrial Common Era}, volume={8}, ISSN={1752-0908}, url={http://dx.doi.org/10.1038/ngeo2510}, DOI={10.1038/ngeo2510}, number={9}, journal={Nature Geoscience}, publisher={Springer Science and Business Media LLC}, author={McGregor, Helen V. and Evans, Michael N. and Goosse, Hugues and Leduc, Guillaume and Martrat, Belen and Addison, Jason A. and Mortyn, P. Graham and Oppo, Delia W. and Seidenkrantz, Marit-Solveig and Sicre, Marie-Alexandrine and Phipps, Steven J. and Selvaraj, Kandasamy and Thirumalai, Kaustubh and Filipsson, Helena L. and Ersek, Vasile}, year={2015}, month=Aug, pages={671–677} }\n', ' @article{Richter_2009, title={Late Holocene (0–2.4 ka BP) surface water temperature and salinity variability, Feni Drift, NE Atlantic Ocean}, volume={28}, ISSN={0277-3791}, url={http://dx.doi.org/10.1016/j.quascirev.2009.04.008}, DOI={10.1016/j.quascirev.2009.04.008}, number={19-20}, journal={Quaternary Science Reviews}, publisher={Elsevier BV}, author={Richter, T.O. and Peeters, F.J.C. and van Weering, T.C.E.}, year={2009}, month=Sept, pages={1941–1955} }\n', '@misc{richter2009httpswwwncdcnoaagovpaleostudy8725DataCitation,\n    author = "T.O. Richter",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/8725"\n}\n', ' @article{Trachsel_2010, title={Scanning reflectance spectroscopy (380–730\xa0nm): a novel method for quantitative high-resolution climate reconstructions from minerogenic lake sediments}, volume={44}, ISSN={1573-0417}, url={http://dx.doi.org/10.1007/s10933-010-9468-7}, DOI={10.1007/s10933-010-9468-7}, number={4}, journal={Journal of Paleolimnology}, publisher={Springer Science and Business Media LLC}, author={Trachsel, M. and Grosjean, M. and Schnyder, D. and Kamenik, C. and Rein, B.}, year={2010}, month=Oct, pages={979–994} }\n', '@misc{trachsel2010httpwwwncdcnoaagovpaleostudy13016DataCitation,\n    author = "M. Trachsel",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/13016"\n}\n', '@misc{nurhati2010httpswwwncdcnoaagovpaleostudy8609DataCitation,\n    author = "I.S. Nurhati",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/8609"\n}\n', '@article{tierney2015tropicalseasurfacetempera,\n    author = "Kevin J. Anchukaitis and Jessica E. Tierney and K. Halimeda Kilbourne and Michael N. Evans and Nerilie J. Abram and Henry C. Wu and Cyril Giry and Casey P. Saenger and Jens Zinke",\n    year = "2015.0",\n    title = "Tropical sea surface temperatures for the past four centuries reconstructed from coral archives",\n    journal = "Paleoceanography",\n    volume = "30",\n    issue = "3.0",\n    pages = "226-252",\n    publisher = "Wiley-Blackwell"\n}\n', '@article{nurhati2011decadalscalesstandsalinit,\n    author = "Emanuele Di Lorenzo and Kim M. Cobb and Intan S. Nurhati",\n    year = "2011.0",\n    title = "Decadal-scale SST and salinity variations in the central tropical Pacific: Signatures of natural and anthropogenic climate change",\n    journal = "Journal of Climate",\n    volume = "24",\n    pages = "3294-3308",\n    publisher = "American Meteorological Society"\n}\n', ' @article{Moses_2006, title={Evidence of multidecadal salinity variability in the eastern tropical North Atlantic}, volume={21}, ISSN={1944-9186}, url={http://dx.doi.org/10.1029/2005PA001257}, DOI={10.1029/2005pa001257}, number={3}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Moses, Christopher S. and Swart, Peter K. and Rosenheim, Brad E.}, year={2006}, month=Aug }\n', '@misc{moses2009httpswwwncdcnoaagovpaleostudy6184DataCitation,\n    author = "C.S. Moses",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/6184"\n}\n', '@misc{moustafa2006httpdoipangaeade101594pangaea388665DataCitation,\n    author = "Y.A. Moustafa",\n    title = "PANGAEA",\n    institution = "PANGAEA",\n    url = "http://doi.pangaea.de/10.1594/PANGAEA.388665"\n}\n', '@article{moustafa2000midholocenestableisotoper,\n    author = "Jürgen Pätzold and Yaser Ahmed Moustafa and Yossi Loya and Gerold Wefer",\n    doi = "http://nbn-resolving.de/urn:nbn:de:gbv:46-ep000102745",\n    year = "2000.0",\n    title = "Mid-Holocene stable isotope record of corals from the northern Red Sea",\n    journal = "Berichte, Fachbereich Geowissenschaften, Universität Bremen",\n    volume = "153",\n    pages = "102 pp"\n}\n', ' @article{Tierney_2015, title={Tropical sea surface temperatures for the past four centuries reconstructed from coral archives}, volume={30}, ISSN={1944-9186}, url={http://dx.doi.org/10.1002/2014PA002717}, DOI={10.1002/2014pa002717}, number={3}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Tierney, Jessica E. and Abram, Nerilie J. and Anchukaitis, Kevin J. and Evans, Michael N. and Giry, Cyril and Kilbourne, K. Halimeda and Saenger, Casey P. and Wu, Henry C. and Zinke, Jens}, year={2015}, month=Mar, pages={226–252} }\n', ' @article{Mart_n_Chivelet_2011, title={Land surface temperature changes in Northern Iberia since 4000yrBP, based on δ13C of speleothems}, volume={77}, ISSN={0921-8181}, url={http://dx.doi.org/10.1016/j.gloplacha.2011.02.002}, DOI={10.1016/j.gloplacha.2011.02.002}, number={1-2}, journal={Global and Planetary Change}, publisher={Elsevier BV}, author={Martín-Chivelet, Javier and Muñoz-García, M. Belén and Edwards, R. Lawrence and Turrero, María J. and Ortega, Ana I.}, year={2011}, month=May, pages={1–12} }\n', '@misc{martin2011httpwwwncdcnoaagovpaleostudy12194DataCitation,\n    author = "J. Martín-Chivelet",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/12194"\n}\n', ' @article{D_Andrea_2012, title={Mild Little Ice Age and unprecedented recent warmth in an 1800 year lake sediment record from Svalbard}, volume={40}, ISSN={1943-2682}, url={http://dx.doi.org/10.1130/G33365.1}, DOI={10.1130/g33365.1}, number={11}, journal={Geology}, publisher={Geological Society of America}, author={D’Andrea, W. J. and Vaillencourt, D. A. and Balascio, N. L. and Werner, A. and Roof, S. R. and Retelle, M. and Bradley, R. S.}, year={2012}, month=Sept, pages={1007–1010} }\n', '@misc{d2012httpswwwncdcnoaagovpaleostudy13458DataCitation,\n    author = "W.J. D\'Andrea",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/13458"\n}\n', ' @article{Abrantes_2011, title={Climate of the last millennium at the southern pole of the North Atlantic Oscillation: an inner-shelf sediment record of flooding and upwelling}, volume={48}, ISSN={1616-1572}, url={http://dx.doi.org/10.3354/cr01010}, DOI={10.3354/cr01010}, number={2}, journal={Climate Research}, publisher={Inter-Research Science Center}, author={Abrantes, F and Rodrigues, T and Montanari, B and Santos, C and Witt, L and Lopes, C and Voelker, AHL}, year={2011}, month=Aug, pages={261–280} }\n', '@misc{abrantes2011httpsdoipangaeade101594pangaea784992DataCitation,\n    author = "F. Abrantes",\n    title = "PANGAEA",\n    institution = "PANGAEA",\n    url = "https://doi.pangaea.de/10.1594/PANGAEA.784992"\n}\n', ' @article{Dorado_Li_n_2012, title={Estimating 750 years of temperature variations and uncertainties in the Pyrenees by tree-ring reconstructions and climate simulations}, volume={8}, ISSN={1814-9332}, url={http://dx.doi.org/10.5194/cp-8-919-2012}, DOI={10.5194/cp-8-919-2012}, number={3}, journal={Climate of the Past}, publisher={Copernicus GmbH}, author={Dorado Liñán, I. and Büntgen, U. and González-Rouco, F. and Zorita, E. and Montávez, J. P. and Gómez-Navarro, J. J. and Brunet, M. and Heinrich, I. and Helle, G. and Gutiérrez, E.}, year={2012}, month=May, pages={919–933} }\n', '@misc{dorado2012httpwwwncdcnoaagovpaleostudy1003405DataCitation,\n    author = "I. Dorado-Linan",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/1003405"\n}\n', ' @article{Helama_2014, title={A palaeotemperature record for the Finnish Lakeland based on microdensitometric variations in tree rings}, volume={41}, ISSN={1897-1695}, url={http://dx.doi.org/10.2478/s13386-013-0163-0}, DOI={10.2478/s13386-013-0163-0}, number={3}, journal={Geochronometria}, publisher={Silesian University of Technology}, author={Helama, Samuli and Vartiainen, Matti and Holopainen, Jari and Mäkelä, Hanna and Kolström, Taneli and Meriläinen, Jouko}, year={2014}, month=June, pages={265–277} }\n', '@misc{helama2014httpwwwncdcnoaagovpaleostudy16790DataCitation,\n    author = "S. Helama",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/16790"\n}\n', '@misc{esper2012httpwwwncdcnoaagovpaleostudy1003406DataCitation,\n    author = "J. Esper",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/1003406"\n}\n', ' @article{Esper_2012, title={Orbital forcing of tree-ring data}, volume={2}, ISSN={1758-6798}, url={http://dx.doi.org/10.1038/nclimate1589}, DOI={10.1038/nclimate1589}, number={12}, journal={Nature Climate Change}, publisher={Springer Science and Business Media LLC}, author={Esper, Jan and Frank, David C. and Timonen, Mauri and Zorita, Eduardo and Wilson, Rob J. S. and Luterbacher, Jürg and Holzkämper, Steffen and Fischer, Nils and Wagner, Sebastian and Nievergelt, Daniel and Verstege, Anne and Büntgen, Ulf}, year={2012}, month=July, pages={862–866} }\n', '@misc{leijonhufvud2010httpwwwncdcnoaagovpaleostudy10429DataCitation,\n    author = "L. Leijonhufvud",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/10429"\n}\n', ' @article{Leijonhufvud_2009, title={Five centuries of Stockholm winter/spring temperatures reconstructed from documentary evidence and instrumental observations}, volume={101}, ISSN={1573-1480}, url={http://dx.doi.org/10.1007/s10584-009-9650-y}, DOI={10.1007/s10584-009-9650-y}, number={1-2}, journal={Climatic Change}, publisher={Springer Science and Business Media LLC}, author={Leijonhufvud, Lotta and Wilson, Rob and Moberg, Anders and Söderberg, Johan and Retsö, Dag and Söderlind, Ulrica}, year={2009}, month=Aug, pages={109–141} }\n']

In [15]:
bibs

['@misc{felis2000httpswwwncdcnoaagovpaleostudy1861DataCitation,\n    author = "T. Felis",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/1861"\n}\n',
 ' @article{Felis_2000, title={A coral oxygen isotope record from the northern Red Sea documenting NAO, ENSO, and North Pacific teleconnections on Middle East climate variability since the year 1750}, volume={15}, ISSN={1944-9186}, url={http://dx.doi.org/10.1029/1999PA000477}, DOI={10.1029/1999pa000477}, number={6}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Felis, Thomas and Pätzold, Jürgen and Loya, Yossi and Fine, Maoz and Nawar, Ahmed H. and Wefer, Gerold}, year={2000}, month=Dec, pages={679–694} }\n',
 ' @article{Tierney_2015, title={Tropical sea surface temperatures for the past four centuries reconstructed from coral archives}, volume={30}, ISSN={1944-9186}, url={http://dx.doi.org/10.1002/2014PA002717}, DOI={10.1002/2014pa002717}, number={3}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Tierney, Jessica E. and Abram, Nerilie J. and Anchukaitis, Kevin J. and Evans, Michael N. and Giry, Cyril and Kilbourne, K. Halimeda and Saenger, Casey P. and Wu, Henry C. and Zinke, Jens}, year={2015}, month=Mar, pages={226–252} }\n',
 '@misc{severinghaus0thisstudyDataCitation,\n    author = "Severinghaus J.",\n    title = "This study",\n    url = "This study"\n}\n',
 ' @article{Orsi_2012, title={Little Ice Age cold interval in West Antarctica: Evidence from borehole temperature at the West Antarctic Ice Sheet (WAIS) Divide}, volume={39}, ISSN={1944-8007}, url={http://dx.doi.org/10.1029/2012GL051260}, DOI={10.1029/2012gl051260}, number={9}, journal={Geophysical Research Letters}, publisher={American Geophysical Union (AGU)}, author={Orsi, Anais J. and Cornuelle, Bruce D. and Severinghaus, Jeffrey P.}, year={2012}, month=May }\n',
 ' @article{Demezhko_2007, title={Climatic changes in the Urals over the past millennium – an analysis of geothermal and meteorological data}, volume={3}, ISSN={1814-9332}, url={http://dx.doi.org/10.5194/cp-3-237-2007}, DOI={10.5194/cp-3-237-2007}, number={2}, journal={Climate of the Past}, publisher={Copernicus GmbH}, author={Demezhko, D. Yu. and Golovanova, I. V.}, year={2007}, month=May, pages={237–242} }\n',
 '@misc{demezhko0thisstudyDataCitation,\n    author = "D Demezhko",\n    title = "This study",\n    url = "this study"\n}\n',
 ' @article{Nieto_Moreno_2013, title={Climate conditions in the westernmost Mediterranean over the last two millennia: An integrated biomarker approach}, volume={55}, ISSN={0146-6380}, url={http://dx.doi.org/10.1016/j.orggeochem.2012.11.001}, DOI={10.1016/j.orggeochem.2012.11.001}, journal={Organic Geochemistry}, publisher={Elsevier BV}, author={Nieto-Moreno, V. and Martínez-Ruiz, F. and Willmott, V. and García-Orellana, J. and Masqué, P. and Sinninghe Damsté, J.S.}, year={2013}, month=Feb, pages={1–10} }\n',
 ' @article{McGregor_2015, title={Robust global ocean cooling trend for the pre-industrial Common Era}, volume={8}, ISSN={1752-0908}, url={http://dx.doi.org/10.1038/ngeo2510}, DOI={10.1038/ngeo2510}, number={9}, journal={Nature Geoscience}, publisher={Springer Science and Business Media LLC}, author={McGregor, Helen V. and Evans, Michael N. and Goosse, Hugues and Leduc, Guillaume and Martrat, Belen and Addison, Jason A. and Mortyn, P. Graham and Oppo, Delia W. and Seidenkrantz, Marit-Solveig and Sicre, Marie-Alexandrine and Phipps, Steven J. and Selvaraj, Kandasamy and Thirumalai, Kaustubh and Filipsson, Helena L. and Ersek, Vasile}, year={2015}, month=Aug, pages={671–677} }\n',
 '@misc{nieto2012httpdoipangaeade101594pangaea802259DataCitation,\n    author = "V. Nieto-Moreno",\n    title = "PANGAEA",\n    institution = "PANGAEA",\n    url = "http://doi.pangaea.de/10.1594/PANGAEA.802259"\n}\n',
 '@misc{mangini2005httpwwwncdcnoaagovpaleostudy5433DataCitation,\n    author = "A. Mangini",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/5433"\n}\n',
 ' @article{Mangini_2005, title={Reconstruction of temperature in the Central Alps during the past 2000 yr from a δ18O stalagmite record}, volume={235}, ISSN={0012-821X}, url={http://dx.doi.org/10.1016/j.epsl.2005.05.010}, DOI={10.1016/j.epsl.2005.05.010}, number={3-4}, journal={Earth and Planetary Science Letters}, publisher={Elsevier BV}, author={Mangini, A. and Spötl, C. and Verdes, P.}, year={2005}, month=July, pages={741–751} }\n',
 ' @article{McGregor_2015, title={Robust global ocean cooling trend for the pre-industrial Common Era}, volume={8}, ISSN={1752-0908}, url={http://dx.doi.org/10.1038/ngeo2510}, DOI={10.1038/ngeo2510}, number={9}, journal={Nature Geoscience}, publisher={Springer Science and Business Media LLC}, author={McGregor, Helen V. and Evans, Michael N. and Goosse, Hugues and Leduc, Guillaume and Martrat, Belen and Addison, Jason A. and Mortyn, P. Graham and Oppo, Delia W. and Seidenkrantz, Marit-Solveig and Sicre, Marie-Alexandrine and Phipps, Steven J. and Selvaraj, Kandasamy and Thirumalai, Kaustubh and Filipsson, Helena L. and Ersek, Vasile}, year={2015}, month=Aug, pages={671–677} }\n',
 ' @article{Richter_2009, title={Late Holocene (0–2.4 ka BP) surface water temperature and salinity variability, Feni Drift, NE Atlantic Ocean}, volume={28}, ISSN={0277-3791}, url={http://dx.doi.org/10.1016/j.quascirev.2009.04.008}, DOI={10.1016/j.quascirev.2009.04.008}, number={19-20}, journal={Quaternary Science Reviews}, publisher={Elsevier BV}, author={Richter, T.O. and Peeters, F.J.C. and van Weering, T.C.E.}, year={2009}, month=Sept, pages={1941–1955} }\n',
 '@misc{richter2009httpswwwncdcnoaagovpaleostudy8725DataCitation,\n    author = "T.O. Richter",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/8725"\n}\n',
 ' @article{Trachsel_2010, title={Scanning reflectance spectroscopy (380–730\xa0nm): a novel method for quantitative high-resolution climate reconstructions from minerogenic lake sediments}, volume={44}, ISSN={1573-0417}, url={http://dx.doi.org/10.1007/s10933-010-9468-7}, DOI={10.1007/s10933-010-9468-7}, number={4}, journal={Journal of Paleolimnology}, publisher={Springer Science and Business Media LLC}, author={Trachsel, M. and Grosjean, M. and Schnyder, D. and Kamenik, C. and Rein, B.}, year={2010}, month=Oct, pages={979–994} }\n',
 '@misc{trachsel2010httpwwwncdcnoaagovpaleostudy13016DataCitation,\n    author = "M. Trachsel",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/13016"\n}\n',
 '@misc{nurhati2010httpswwwncdcnoaagovpaleostudy8609DataCitation,\n    author = "I.S. Nurhati",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/8609"\n}\n',
 '@article{tierney2015tropicalseasurfacetempera,\n    author = "Kevin J. Anchukaitis and Jessica E. Tierney and K. Halimeda Kilbourne and Michael N. Evans and Nerilie J. Abram and Henry C. Wu and Cyril Giry and Casey P. Saenger and Jens Zinke",\n    year = "2015.0",\n    title = "Tropical sea surface temperatures for the past four centuries reconstructed from coral archives",\n    journal = "Paleoceanography",\n    volume = "30",\n    issue = "3.0",\n    pages = "226-252",\n    publisher = "Wiley-Blackwell"\n}\n',
 '@article{nurhati2011decadalscalesstandsalinit,\n    author = "Emanuele Di Lorenzo and Kim M. Cobb and Intan S. Nurhati",\n    year = "2011.0",\n    title = "Decadal-scale SST and salinity variations in the central tropical Pacific: Signatures of natural and anthropogenic climate change",\n    journal = "Journal of Climate",\n    volume = "24",\n    pages = "3294-3308",\n    publisher = "American Meteorological Society"\n}\n',
 ' @article{Moses_2006, title={Evidence of multidecadal salinity variability in the eastern tropical North Atlantic}, volume={21}, ISSN={1944-9186}, url={http://dx.doi.org/10.1029/2005PA001257}, DOI={10.1029/2005pa001257}, number={3}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Moses, Christopher S. and Swart, Peter K. and Rosenheim, Brad E.}, year={2006}, month=Aug }\n',
 '@misc{moses2009httpswwwncdcnoaagovpaleostudy6184DataCitation,\n    author = "C.S. Moses",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/6184"\n}\n',
 '@misc{moustafa2006httpdoipangaeade101594pangaea388665DataCitation,\n    author = "Y.A. Moustafa",\n    title = "PANGAEA",\n    institution = "PANGAEA",\n    url = "http://doi.pangaea.de/10.1594/PANGAEA.388665"\n}\n',
 '@article{moustafa2000midholocenestableisotoper,\n    author = "Jürgen Pätzold and Yaser Ahmed Moustafa and Yossi Loya and Gerold Wefer",\n    doi = "http://nbn-resolving.de/urn:nbn:de:gbv:46-ep000102745",\n    year = "2000.0",\n    title = "Mid-Holocene stable isotope record of corals from the northern Red Sea",\n    journal = "Berichte, Fachbereich Geowissenschaften, Universität Bremen",\n    volume = "153",\n    pages = "102 pp"\n}\n',
 ' @article{Tierney_2015, title={Tropical sea surface temperatures for the past four centuries reconstructed from coral archives}, volume={30}, ISSN={1944-9186}, url={http://dx.doi.org/10.1002/2014PA002717}, DOI={10.1002/2014pa002717}, number={3}, journal={Paleoceanography}, publisher={American Geophysical Union (AGU)}, author={Tierney, Jessica E. and Abram, Nerilie J. and Anchukaitis, Kevin J. and Evans, Michael N. and Giry, Cyril and Kilbourne, K. Halimeda and Saenger, Casey P. and Wu, Henry C. and Zinke, Jens}, year={2015}, month=Mar, pages={226–252} }\n',
 ' @article{Mart_n_Chivelet_2011, title={Land surface temperature changes in Northern Iberia since 4000yrBP, based on δ13C of speleothems}, volume={77}, ISSN={0921-8181}, url={http://dx.doi.org/10.1016/j.gloplacha.2011.02.002}, DOI={10.1016/j.gloplacha.2011.02.002}, number={1-2}, journal={Global and Planetary Change}, publisher={Elsevier BV}, author={Martín-Chivelet, Javier and Muñoz-García, M. Belén and Edwards, R. Lawrence and Turrero, María J. and Ortega, Ana I.}, year={2011}, month=May, pages={1–12} }\n',
 '@misc{martin2011httpwwwncdcnoaagovpaleostudy12194DataCitation,\n    author = "J. Martín-Chivelet",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/12194"\n}\n',
 ' @article{D_Andrea_2012, title={Mild Little Ice Age and unprecedented recent warmth in an 1800 year lake sediment record from Svalbard}, volume={40}, ISSN={1943-2682}, url={http://dx.doi.org/10.1130/G33365.1}, DOI={10.1130/g33365.1}, number={11}, journal={Geology}, publisher={Geological Society of America}, author={D’Andrea, W. J. and Vaillencourt, D. A. and Balascio, N. L. and Werner, A. and Roof, S. R. and Retelle, M. and Bradley, R. S.}, year={2012}, month=Sept, pages={1007–1010} }\n',
 '@misc{d2012httpswwwncdcnoaagovpaleostudy13458DataCitation,\n    author = "W.J. D\'Andrea",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "https://www.ncdc.noaa.gov/paleo/study/13458"\n}\n',
 ' @article{Abrantes_2011, title={Climate of the last millennium at the southern pole of the North Atlantic Oscillation: an inner-shelf sediment record of flooding and upwelling}, volume={48}, ISSN={1616-1572}, url={http://dx.doi.org/10.3354/cr01010}, DOI={10.3354/cr01010}, number={2}, journal={Climate Research}, publisher={Inter-Research Science Center}, author={Abrantes, F and Rodrigues, T and Montanari, B and Santos, C and Witt, L and Lopes, C and Voelker, AHL}, year={2011}, month=Aug, pages={261–280} }\n',
 '@misc{abrantes2011httpsdoipangaeade101594pangaea784992DataCitation,\n    author = "F. Abrantes",\n    title = "PANGAEA",\n    institution = "PANGAEA",\n    url = "https://doi.pangaea.de/10.1594/PANGAEA.784992"\n}\n',
 ' @article{Dorado_Li_n_2012, title={Estimating 750 years of temperature variations and uncertainties in the Pyrenees by tree-ring reconstructions and climate simulations}, volume={8}, ISSN={1814-9332}, url={http://dx.doi.org/10.5194/cp-8-919-2012}, DOI={10.5194/cp-8-919-2012}, number={3}, journal={Climate of the Past}, publisher={Copernicus GmbH}, author={Dorado Liñán, I. and Büntgen, U. and González-Rouco, F. and Zorita, E. and Montávez, J. P. and Gómez-Navarro, J. J. and Brunet, M. and Heinrich, I. and Helle, G. and Gutiérrez, E.}, year={2012}, month=May, pages={919–933} }\n',
 '@misc{dorado2012httpwwwncdcnoaagovpaleostudy1003405DataCitation,\n    author = "I. Dorado-Linan",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/1003405"\n}\n',
 ' @article{Helama_2014, title={A palaeotemperature record for the Finnish Lakeland based on microdensitometric variations in tree rings}, volume={41}, ISSN={1897-1695}, url={http://dx.doi.org/10.2478/s13386-013-0163-0}, DOI={10.2478/s13386-013-0163-0}, number={3}, journal={Geochronometria}, publisher={Silesian University of Technology}, author={Helama, Samuli and Vartiainen, Matti and Holopainen, Jari and Mäkelä, Hanna and Kolström, Taneli and Meriläinen, Jouko}, year={2014}, month=June, pages={265–277} }\n',
 '@misc{helama2014httpwwwncdcnoaagovpaleostudy16790DataCitation,\n    author = "S. Helama",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/16790"\n}\n',
 '@misc{esper2012httpwwwncdcnoaagovpaleostudy1003406DataCitation,\n    author = "J. Esper",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/1003406"\n}\n',
 ' @article{Esper_2012, title={Orbital forcing of tree-ring data}, volume={2}, ISSN={1758-6798}, url={http://dx.doi.org/10.1038/nclimate1589}, DOI={10.1038/nclimate1589}, number={12}, journal={Nature Climate Change}, publisher={Springer Science and Business Media LLC}, author={Esper, Jan and Frank, David C. and Timonen, Mauri and Zorita, Eduardo and Wilson, Rob J. S. and Luterbacher, Jürg and Holzkämper, Steffen and Fischer, Nils and Wagner, Sebastian and Nievergelt, Daniel and Verstege, Anne and Büntgen, Ulf}, year={2012}, month=July, pages={862–866} }\n',
 '@misc{leijonhufvud2010httpwwwncdcnoaagovpaleostudy10429DataCitation,\n    author = "L. Leijonhufvud",\n    title = "World Data Center for Paleoclimatology",\n    institution = "World Data Center for Paleoclimatology",\n    url = "http://www.ncdc.noaa.gov/paleo/study/10429"\n}\n',
 ' @article{Leijonhufvud_2009, title={Five centuries of Stockholm winter/spring temperatures reconstructed from documentary evidence and instrumental observations}, volume={101}, ISSN={1573-1480}, url={http://dx.doi.org/10.1007/s10584-009-9650-y}, DOI={10.1007/s10584-009-9650-y}, number={1-2}, journal={Climatic Change}, publisher={Springer Science and Business Media LLC}, author={Leijonhufvud, Lotta and Wilson, Rob and Moberg, Anders and Söderberg, Johan and Retsö, Dag and Söderlind, Ulrica}, year={2009}, month=Aug, pages={109–141} }\n']

In [17]:
df.head()

,dsname,title,authors,doi,pubyear,year,journal,volume,issue,pages,type,publisher,report,citeKey,edition,institution,url,url2
0,Ocn-RedSea.Felis.2000,World Data Center for Paleoclimatology,T. Felis,NaN,None,NaN,NaN,NaN,None,NaN,dataCitation,NaN,None,felis2000httpswwwncdcnoaagovpaleostudy1861Data...,None,World Data Center for Paleoclimatology,None,https://www.ncdc.noaa.gov/paleo/study/1861
1,Ocn-RedSea.Felis.2000,A coral oxygen isotope record from the norther...,Jürgen Pätzold and Yossi Loya and Thomas Felis...,10.1029/1999PA000477,None,2000.0,Paleoceanography,15,6.0,679-694,article,Wiley-Blackwell,None,felis2000acoraloxygenisotoperecord,None,NaN,None,NaN
2,Ocn-RedSea.Felis.2000,Tropical sea surface temperatures for the past...,Kevin J. Anchukaitis and Michael N. Evans and ...,10.1002/2014PA002717,None,2015.0,Paleoceanography,30,3.0,226-252,journal-article,Wiley-Blackwell,None,tierney2015tropicalseasurfacetempera,None,NaN,None,NaN
3,Ant-WAIS-Divide.Severinghaus.2012,This study,Severinghaus J.,NaN,None,NaN,NaN,NaN,None,NaN,dataCitation,NaN,None,severinghaus0thisstudyDataCitation,None,NaN,None,This study
4,Ant-WAIS-Divide.Severinghaus.2012,Little Ice Age cold interval in West Antarctic...,Bruce D. Cornuelle and Jeffrey P. Severinghaus...,10.1029/2012GL051260,None,2012.0,Geophysical Research Letters,39,9.0,L09710,article,Wiley-Blackwell,None,orsi2012littleiceagecoldintervali,None,NaN,None,NaN

## Datasets that should be cited

This notebook uses the following datasets, which should appear in a generated bibliography:

- **Ocn-RedSea.Felis.2000** — Felis, T. et al. (2000). Coral d18O from the northern Red Sea. *Paleoceanography*, 15(6), 679–694. doi:10.1029/1999PA000477
- **Nunalleq.Ledger.2018** — Ledger, P. M. et al. (2018). Climate reconstruction from archaeological site Nunalleq, Alaska.
- **Ocn-Palmyra.Nurhati.2011** — Nurhati, I. S., Cobb, K. M., & Di Lorenzo, E. (2011). Decadal-scale SST and salinity variations in the central tropical Pacific. *Journal of Climate*, 24(13), 3294–3308. doi:10.1175/2011JCLI3852.1
- **Pages2k directory** (17 datasets) — including Felis.2000, Severinghaus.2012, Demezhko.2007, Nieto-Moreno.2013, Mangini.2005, Richter.2009, Trachsel.2010, Nurhati.2011, Moses.2006, Moustafa.2000, Martin-Chivelet.2011, D_Andrea.2012, Abrantes.2011, Dorado-Linan.2012, Helama.2014, Esper.2012, Leijonhufvud.2009
- **MD98_2181.Stott.2007** — Stott, L. et al. (2007). Deep sea sediment core MD98-2181 from the western Pacific warm pool.
- **Ocn-MadangLagoonPapuaNewGuinea.Kuhnert.2001** — Kuhnert, H. et al. (2001). Coral record from Madang Lagoon, Papua New Guinea.